function generateRecipe(event) {
  event.preventDefault();

  let userInput = document.querySelector("#user-input");

  let apiKey = `d37e0bate3co638094f17bb45fdb3101`;
  let prompt = `generate a recipe for ${userInput.value}`;
  let context = `you like to provide clear and easy instructions only. separate the ingredients and the steps by a new line. Sign the recipe with "Generated by SheCodes AI" at the bottom in #f56262`;
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  let examples = document.querySelector(".examples");
  examples.classList.add(`hidden`);

  let recipeBlock = document.querySelector(`#recipe`);
  recipeBlock.classList.remove(`hidden`);

  new Typewriter("#recipe", {
    strings: `Generating Recipe for ${userInput.value}...`,
    autoStart: true,
    delay: 5,
    cursor: null,
  });
  axios.get(apiUrl).then(displayRecipe);
}

function displayRecipe(event) {
  new Typewriter("#recipe", {
    strings: event.data.answer,
    autoStart: true,
    delay: 1,
    cursor: null,
  });
}

let recipeInput = document.querySelector("#recipe-generator-form");
recipeInput.addEventListener("submit", generateRecipe);
